apiVersion: v2
name: fourlanchesk8s
description: A Helm chart for FourLanches.
version: 0.1.0
dependencies:
  - name: order-app
    version: 0.1.0
    repository: "file://charts/order"
    condition: order-app.enabled
  - name: payment-app
    version: 0.1.0
    repository: "file://charts/payment"
    condition: payment-app.enabled
  - name: kitchen-app
    version: 0.1.0
    repository: "file://charts/kitchen"
    condition: kitchen-app.enabled
  - name: customer-app
    version: 0.1.0
    repository: "file://charts/customer"
    condition: customer-app.enabled
  - name: sonarqube
    version: 0.1.0
    repository: "file://charts/sonarqube"
    condition: sonarqube.enabled