### Global Values if any ###
global: {
  kubernetesClusterDomain: fourlanchesk8s
}

### Sub Charts Specific Values ###
kitchen-app:
  enabled: true
  deployment:
    replicaCount: 1
order-app:
  enabled: true
  deployment:
    replicaCount: 1
payment-app:
  enabled: true
  deployment:
    replicaCount: 1
customer-app:
  enabled: true
  deployment:
    replicaCount: 1
sonarqube:
  enabled: false
  deployment:
    replicaCount: 1

secrets:
  databaseLogin: ${DATABASE_LOGIN}
  databasePassword: ${DATABASE_PASSWORD}
  mongoPaymentConnectionString: ${MONGO_PAYMENTS_CONN_STRING}

configs:
  postgresqlDatasourceUrl: ${PSQL_DATASOURCE}
  mysqlDatasourceUrl: ${MYSQL_DATASOURCE}
  springJpaHibernateDdlAuto: none
