apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "order-app.fullname" . }}-config
        - secretRef:
            name: {{ include "order-app.fullname" . }}-secret
        image: {{ .Values.deployment.orderApp.image.repository }}:{{ .Values.deployment.orderApp.image.tag }}
        imagePullPolicy: {{ .Values.deployment.orderApp.imagePullPolicy }}
        name: order
        ports:
        - containerPort: 8080
        resources: {}