apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "order-app.name" . }}-flyway-migration
  labels:
  {{- include "order-app.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - args: [info, repair, migrate, info]
        env:
        - name: FLYWAY_URL
          valueFrom:
            configMapKeyRef:
              key: POSTGRESQL_DATASOURCE_URL
              name: {{ .Values.deployment.configRef }}
        - name: FLYWAY_USER
          valueFrom:
            secretKeyRef:
              key: DATABASE_USERNAME
              name: {{ .Values.deployment.secretRef }}
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATABASE_PASSWORD
              name: {{ .Values.deployment.secretRef }}
        image: flyway/flyway:latest
        name: flyway
        resources: {}
        volumeMounts:
        - mountPath: /flyway/sql
          name: sql
      restartPolicy: Never
      volumes:
      - configMap:
          name: {{ include "order-app.fullname" . }}-flyway-config
        name: sql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-app.fullname" . }}-flyway-config
  labels:
  {{- include "order-app.labels" . | nindent 4 }}
data:
  V1__Create_Product_Table.sql: {{ .Values.flywayConfig.v1CreateProductTableSql |
    toYaml | indent 1 }}
  V2__Add_Initial_Products.sql: {{ .Values.flywayConfig.v2AddInitialProductsSql |
    toYaml | indent 1 }}
  V3__Create_Order_Table.sql: {{ .Values.flywayConfig.v3CreateOrderTableSql | toYaml
    | indent 1 }}
  V4__Create_Order_Item_Table.sql: {{ .Values.flywayConfig.v4CreateOrderItemTableSql
    | toYaml | indent 1 }}
  V5__Create_Customer_Table.sql: {{ .Values.flywayConfig.v5CreateCustomerTableSql
    | toYaml | indent 1 }}
  V6__Add_Column_Payment_To_Order.sql: {{ .Values.flywayConfig.v6AddColumnPaymentToOrderSql
    | toYaml | indent 1 }}
  V7__Add_Column_Created_At_To_Order.sql: {{ .Values.flywayConfig.v7AddColumnCreatedAtToOrderSql
    |  toYaml | indent 1 }}