apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-app.name" . }}-service
  labels:
    {{ include "order-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    {{ include "order-app.selectorLabels" . | nindent 6 }}