apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "customer-app.name" . }}
  labels:
    {{ include "customer-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{ include "customer-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "customer-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
          - configMapRef:
              name: {{ .Values.deployment.configRef }}
          - secretRef:
              name: {{ .Values.deployment.secretRef }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}