apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sonarqube.name" . }}
  labels:
    {{ include "sonarqube.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{ include "sonarqube.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sonarqube.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
      containers:
        - name: {{ include "sonarqube.name" . }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          ports:
            - containerPort: 9000
          env:
            - name: SONAR_JDBC_URL        
              valueFrom:
                configMapKeyRef:
                  key: SONAR_DATASOURCE_URL
                  name: {{ .Values.deployment.configRef }}
            - name: SONAR_JDBC_USERNAME        
              valueFrom:
                secretKeyRef:
                  key: PSQL_USERNAME
                  name: {{ .Values.deployment.secretRef }}
            - name: SONAR_JDBC_PASSWORD        
              valueFrom:
                secretKeyRef:
                  key: PSQL_PASSWORD
                  name: {{ .Values.deployment.secretRef }}
            - name: SONAR_WEB_HOST
              value: 0.0.0.0
            - name: SONAR_WEB_CONTEXT
              value: "/"
            - name: SONAR_JDBC_MAXACTIVE
              value: "20"
            - name: SONAR_JDBC_MAXIDLE
              value: "5"
            - name: SONAR_JDBC_MINIDLE
              value: "1"
            - name: SONAR_JDBC_MAXWAIT
              value: "5000"
          resources:
            requests:
              memory: "512Mi"
              cpu: "600m"
            limits:
              memory: "1.5Gi"
              cpu: "1200m"