apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonarqube.name" . }}-service
  labels:
    {{ include "sonarqube.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9000
  selector:
    {{ include "sonarqube.selectorLabels" . | nindent 6 }}