apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fourlanches-app.fullname" . }}-flyway-config
  labels:
  {{- include "fourlanches-app.labels" . | nindent 4 }}
data:
  V1__Create_Product_Table.sql: {{ .Values.flywayConfig.v1CreateProductTableSql |
    toYaml | indent 1 }}
  V2__Add_Initial_Products.sql: {{ .Values.flywayConfig.v2AddInitialProductsSql |
    toYaml | indent 1 }}
  V3__Create_Order_Table.sql: {{ .Values.flywayConfig.v3CreateOrderTableSql | toYaml
    | indent 1 }}
  V4__Create_Order_Item_Table.sql: {{ .Values.flywayConfig.v4CreateOrderItemTableSql
    | toYaml | indent 1 }}
  V5__Create_Customer_Table.sql: {{ .Values.flywayConfig.v5CreateCustomerTableSql
    | toYaml | indent 1 }}
  V6__Add_Column_Payment_To_Order.sql: {{ .Values.flywayConfig.v6AddColumnPaymentToOrderSql
    | toYaml | indent 1 }}