apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fourlanches-app.fullname" . }}-secret
  labels:
    app: fourlanches
  {{- include "fourlanches-app.labels" . | nindent 4 }}
stringData:
  SPRING_DATASOURCE_USERNAME: {{ required "secrets.springDatasourceUsername is required" .Values.secrets.springDatasourceUsername | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ required "secrets.springDatasourcePassword is required" .Values.secrets.springDatasourcePassword | quote }}