apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: fourlanches
  {{- include "fourlanches-app.labels" . | nindent 4 }}
data:
  POSTGRESQL_DATASOURCE_URL: {{ .Values.configs.postgresqlDatasourceUrl | quote }}
  MYSQL_DATASOURCE_URL: {{ .Values.configs.mysqlDatasourceUrl | quote }}
  RABBITMQ_HOST: {{ .Values.configs.rabbitmqHost | quote }}
  RABBITMQ_PORT: {{ .Values.configs.rabbitmqPort | quote }}
  RABBITMQ_VHOST: {{ .Values.configs.rabbitmqVhost | quote }}
