apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: fourlanches
  {{- include "fourlanches-app.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.configs.springDatasourceUrl | quote
    }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.configs.springJpaHibernateDdlAuto
    | quote }}
