apiVersion: v1
kind: Service
metadata:
  name: {{ include "fourlanches-app.fullname" . }}-loadbalancer
  labels:
  {{- include "fourlanches-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.loadBalancer.type }}
  selector:
    app: fourlanches
  {{- include "fourlanches-app.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.loadBalancer.ports | toYaml | nindent 2 -}}