apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    app: fourlanches
  {{- include "fourlanches-app.labels" . | nindent 4 }}
stringData:
  SPRING_DATASOURCE_USERNAME: {{ required "secrets.springDatasourceUsername is required" .Values.secrets.springDatasourceUsername | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ required "secrets.springDatasourcePassword is required" .Values.secrets.springDatasourcePassword | quote }}
  PAYMENT_DB_CONNECTION_STRING: {{ required "secrets.mongoConnectionString is required" .Values.secrets.mongoConnectionString | quote }}