apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    app: fourlanches
  {{- include "fourlanches-app.labels" . | nindent 4 }}
stringData:
  DATABASE_USERNAME: {{ required "secrets.databaseUsername is required" .Values.secrets.databaseUsername | quote }}
  DATABASE_PASSWORD: {{ required "secrets.databasePassword is required" .Values.secrets.databasePassword | quote }}
  PAYMENT_DB_CONNECTION_STRING: {{ required "secrets.mongoPaymentConnectionString is required" .Values.secrets.mongoPaymentConnectionString | quote }}