apiVersion: v1
kind: Service
metadata:
  name: payment-app-service
  labels:
    app: fourlanches
  {{- include "fourlanches-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.fourlanchesSvc.type }}
  selector:
    app: payment-app
  {{- include "fourlanches-app.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.fourlanchesSvc.ports | toYaml | nindent 2 -}}
