name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace Secrets in Helm Values
      run: |
        DB_USER=${{ secrets.DB_USER }}
        DB_PASSWORD="${{ secrets.DB_PASSWORD }}
        DB_HOST=${{ secrets.DB_HOST }}
        sed -i -e 's|{{ DB_HOST }}|'"$DB_HOST"'|g;s|{{ DB_USER }}|'"$DB_USER"'|g;s|{{ DB_PASSWORD }}|'"$DB_PASSWORD"'|g' fourlanches-app/values.yaml
    - name: Deploy to Kubernetes
      run: |
        helm install fourlanches-app fourlanches-app -f fourlanches-app/values.yaml
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
