name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace Secrets in Helm Values
      run: |
        export DB_USER=${{ secrets.DB_USER }}
        export DB_PASSWORD="${{ secrets.DB_PASSWORD }}
        export DB_HOST=${{ secrets.DB_HOST }}
        envsubst < fourlanches-app/values.yaml > fourlanches-app/values-updated.yaml
        mv fourlanches-app/values-updated.yaml fourlanches-app/values.yaml
    - name: Deploy to Kubernetes
      run: |
        helm install fourlanches-app fourlanches-app -f fourlanches-app/values.yaml
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
