name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v1.4.6
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Set up kubelogin for non-interactive login
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.0.25'

    - name: Get K8s context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}
        admin: 'false'
        use-kubelogin: 'true'

    - name: Replace Secrets in Helm Values
      run: |
        export DB_USER=${{ secrets.DB_USER }}
        export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        export DB_HOST=${{ secrets.DB_HOST }}
        envsubst < fourlanches-app/values.yaml > fourlanches-app/values-updated.yaml
        mv fourlanches-app/values-updated.yaml fourlanches-app/values.yaml

    - uses: azure/k8s-bake@v2.4
      with:
         renderEngine: 'helm'
         helmChart: './fourlanches-app/'
         overrideFiles: './fourlanches-app/values.yaml'
         helm-version: 'latest'
      id: bake

    - uses: Azure/k8s-deploy@v4
      with:
         manifests: ${{ steps.bake.outputs.manifestsBundle }}